name: /home/wangzihan/condaenv/vllm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.9=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.30.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.47.0=hadc24fc_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.4.0=hb9d3cd8_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.0=py310ha75aee5_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_1
  - python=3.10.15=h4a871b0_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=5_cp310
  - pyzmq=26.2.0=py310h71f11fc_3
  - readline=8.2=h8228510_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py310ha75aee5_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h3b0a872_7
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - bert-score==0.3.13
      - bitsandbytes==0.44.1
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - compressed-tensors==0.6.0
      - conda-pack==0.8.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.0.2
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - einops==0.8.0
      - evaluate==0.4.3
      - fastapi==0.115.4
      - filelock==3.16.1
      - flash-attn==2.7.2.post1
      - fonttools==4.59.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gguf==0.10.0
      - google-api-core==2.24.0
      - google-api-python-client==2.155.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.66.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.27.2
      - huggingface-hub==0.26.2
      - idna==3.10
      - interegular==0.3.3
      - jinja2==3.1.4
      - jiter==0.7.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - langdetect==1.0.9
      - lark==1.2.2
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.6
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mistral-common==1.4.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.18.6
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - nltk==3.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.54.0
      - opencv-python-headless==4.10.0.84
      - outlines==0.0.46
      - packaging==24.1
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post4
      - peft==0.13.2
      - pillow==10.4.0
      - prometheus-client==0.21.0
      - prometheus-fastapi-instrumentator==7.0.0
      - propcache==0.2.0
      - proto-plus==1.25.0
      - protobuf==5.28.3
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==18.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycountry==24.6.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.2.0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - ray==2.38.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - rouge-score==0.1.2
      - rpds-py==0.20.1
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - six==1.16.0
      - sniffio==1.3.1
      - starlette==0.41.2
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tiktoken==0.7.0
      - tokenizers==0.20.2
      - torch==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.6
      - transformers==4.46.1
      - triton==3.0.0
      - tzdata==2024.2
      - uritemplate==4.1.1
      - urllib3==2.2.3
      - uvicorn==0.32.0
      - uvloop==0.21.0
      - vllm==0.6.3.post1
      - watchfiles==0.24.0
      - websockets==13.1
      - xformers==0.0.27.post2
      - xxhash==3.5.0
      - yarl==1.17.1
      - zipp==3.20.2
prefix: /home/wangzihan/condaenv/vllm
